"""Adding deletion stuff

Revision ID: 0ad4ee7940e6
Revises: f2ee73d17a0c
Create Date: 2024-01-27 12:54:59.708632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad4ee7940e6'
down_revision: Union[str, None] = 'f2ee73d17a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversation_document_conversation_id_fkey', 'conversation_document', type_='foreignkey')
    op.drop_constraint('conversation_document_document_id_fkey', 'conversation_document', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_document', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversation_document', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_document', type_='foreignkey')
    op.drop_constraint(None, 'conversation_document', type_='foreignkey')
    op.create_foreign_key('conversation_document_document_id_fkey', 'conversation_document', 'document', ['document_id'], ['id'])
    op.create_foreign_key('conversation_document_conversation_id_fkey', 'conversation_document', 'conversation', ['conversation_id'], ['id'])
    # ### end Alembic commands ###
