"""Adding index ID to document

Revision ID: 277315defa40
Revises: d0553d0470db
Create Date: 2024-02-19 16:06:02.719326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277315defa40'
down_revision: Union[str, None] = 'd0553d0470db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('pinecone_index_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'pinecone_index_id')
    # ### end Alembic commands ###
