"""Adding conversation title

Revision ID: 34987efe6d23
Revises: 0ad4ee7940e6
Create Date: 2024-01-27 14:01:30.856147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34987efe6d23'
down_revision: Union[str, None] = '0ad4ee7940e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'title')
    # ### end Alembic commands ###
