"""Last updated for conversation migration

Revision ID: 3b6539d2bf43
Revises: fa709eee84df
Create Date: 2024-01-21 17:28:49.049300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6539d2bf43'
down_revision: Union[str, None] = 'fa709eee84df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'last_updated_at')
    # ### end Alembic commands ###
