"""Adding user to a file

Revision ID: c27c4608717b
Revises: 7dbd0c6c9d86
Create Date: 2024-01-22 20:52:48.124254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27c4608717b'
down_revision: Union[str, None] = '7dbd0c6c9d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'user_id')
    # ### end Alembic commands ###
