"""Updating model

Revision ID: d0553d0470db
Revises: 34987efe6d23
Create Date: 2024-02-05 19:44:12.916467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0553d0470db'
down_revision: Union[str, None] = '34987efe6d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('profile_picture_s3_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture_s3_link')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
