"""Initial migration

Revision ID: df631cfbc150
Revises: 
Create Date: 2024-01-21 15:27:13.302840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df631cfbc150'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('conversation', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversation', 'user', ['user_id'], ['id'])
    op.drop_column('conversation', 'prompt')
    op.drop_column('conversation', 'response')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.add_column('conversation', sa.Column('response', sa.VARCHAR(length=1280), autoincrement=False, nullable=True))
    op.add_column('conversation', sa.Column('prompt', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.drop_column('conversation', 'user_id')
    op.drop_column('conversation', 'created_at')
    # ### end Alembic commands ###
